language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "9"
  - "8"
  - "6"
  - "4"
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
  - npm run test:karma
  - npm run test:nsp
  #- MR_VERSION=. MOP_VERSION="0.13" npm run integration
  - MR_VERSION=. MOP_VERSION="latest" npm run integration
  - MR_VERSION=. MOP_VERSION="#master" npm run integration